apiVersion: v1
kind: Namespace
metadata:
  name: testing
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: testing
  name: testing-deployment
  labels:
    app: testing
spec:
  replicas: 3
  selector:
    matchLabels:
      app: testing
  template:
    metadata:
      labels:
        app: testing
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - testing
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: testing
        image: crossrt/assessment-ray-nodejs-app:latest
        ports:
        - containerPort: 1234
        env:
        - name: PORT
          value: "1234"
        readinessProbe:
          httpGet:
            path: /
            port: 1234
          initialDelaySeconds: 3
          periodSeconds: 3
          timeoutSeconds: 2
      securityContext:
        fsGroup: 65534
---
apiVersion: v1
kind: Service
metadata:
  namespace: testing
  name: testing-service
spec:
  type: NodePort
  selector:
    app: testing
  ports:
    - port: 1234
      nodePort: 31234
---
